"""
wc_tactics.py — Tactical matchup and set-piece features for WC 2026 model.

Provides:
    - MatchSummary: per-match input stats for one team
    - TacticalProfile: rolling EWMA tactical state per team
    - StyleMatchup: cross-team interaction features for a matchup
    - TacticalEngine: stateful engine computing profiles and matchup interactions

TACTICAL-01: PPDA proxy and possession style index (rolling EWMA)
TACTICAL-02: Counterattack frequency and rest-defense stability
TACTICAL-03: Style matchup interactions (press-vs-build, width-vs-centrality,
             possession-vs-transition)
TACTICAL-04: Set-piece attack/defense EWMA states, SEPARATE from open-play xG
TACTICAL-05: Corner xG for/against and aerial duel edge
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# Input data structure
# ---------------------------------------------------------------------------

@dataclass
class MatchSummary:
    """
    Per-match statistics for one team — input to TacticalEngine.update().

    All stats represent the named team's performance in a single match.

    Attributes
    ----------
    team : str
    ppda : float
        Passes Per Defensive Action (opponent passes / team def. actions).
        Lower PPDA = more pressing. Typical range 5–20.
    possession : float
        Ball possession percentage (0–100).
    transitions : int
        Counterattack opportunities created (team transitions into attack
        after winning the ball in own half).
    rest_defense_conceded : int
        Goals conceded while opponent was transitioning (rest-defense failures).
    rest_defense_transitions_faced : int
        Number of opponent transitions the team had to defend.
    sp_xg_for : float
        Set-piece expected goals generated by this team (corners + FKs).
    sp_xg_against : float
        Set-piece xG conceded by this team.
    corner_xg_for : float
        Corner-specific xG generated.
    corner_xg_against : float
        Corner-specific xG conceded.
    aerial_duels_won_rate : float
        Fraction of aerial duels won (0–1).
    open_play_xg_for : float
        Open-play xG for (NOT set-piece). Used separately from sp_xg.
    open_play_xg_against : float
        Open-play xG against (NOT set-piece).
    """
    team: str
    ppda: float = 10.0
    possession: float = 50.0
    transitions: int = 5
    rest_defense_conceded: int = 0
    rest_defense_transitions_faced: int = 5
    sp_xg_for: float = 0.0
    sp_xg_against: float = 0.0
    corner_xg_for: float = 0.0
    corner_xg_against: float = 0.0
    aerial_duels_won_rate: float = 0.5
    open_play_xg_for: float = 1.0
    open_play_xg_against: float = 1.0


# ---------------------------------------------------------------------------
# Output data structures
# ---------------------------------------------------------------------------

@dataclass
class TacticalProfile:
    """
    Rolling EWMA tactical state for a team.

    Fields are EWMA-smoothed values from multiple MatchSummary inputs.

    TACTICAL-01
    -----------
    ppda : float
        Exponentially-weighted PPDA. Lower = more pressing.
    possession_index : float
        Possession fraction (0–1) EWMA. 0=pure counter, 1=pure possession.

    TACTICAL-02
    -----------
    counterattack_freq : float
        Average transitions created per match (EWMA).
    rest_defense_stability : float
        Fraction of opposition transitions defended without conceding (EWMA).
        1.0 = perfect, 0.0 = always conceded.

    TACTICAL-04 (separate from open-play)
    -----------
    sp_xg_for_ewma : float
        Set-piece xG generated per match (EWMA).
    sp_xg_against_ewma : float
        Set-piece xG conceded per match (EWMA).

    TACTICAL-05
    -----------
    corner_xg_for_ewma : float
        Corner-specific xG per match (EWMA).
    corner_xg_against_ewma : float
        Corner xG conceded per match (EWMA).
    aerial_duel_edge : float
        Team aerial duel win rate minus 0.5. Positive = aerial advantage.

    Open-play xG (kept separate, NOT mixed with set-piece)
    --------------------
    open_xg_for_ewma : float
    open_xg_against_ewma : float
    """
    team: str
    # TACTICAL-01
    ppda: float = 10.0
    possession_index: float = 0.5
    # TACTICAL-02
    counterattack_freq: float = 0.0
    rest_defense_stability: float = 1.0
    # TACTICAL-04: set-piece EWMA (separate state)
    sp_xg_for_ewma: float = 0.0
    sp_xg_against_ewma: float = 0.0
    # TACTICAL-05
    corner_xg_for_ewma: float = 0.0
    corner_xg_against_ewma: float = 0.0
    aerial_duel_edge: float = 0.0
    # Open-play xG (separate tracking)
    open_xg_for_ewma: float = 1.0
    open_xg_against_ewma: float = 1.0


@dataclass
class StyleMatchup:
    """
    Cross-team style interaction features for a home vs away matchup.

    Computed as team_A_feature × opponent_B_vulnerability (TACTICAL-03).
    Positive = home-team advantage; negative = away advantage.

    Attributes
    ----------
    press_vs_build : float
        (home pressing intensity) × (away possession index).
        High = home press threatens away build-up play.
    width_vs_centrality : float
        (home counterattack frequency) × (1 - away rest_defense_stability).
        High = home width/transitions exploit away defensive shape.
    possession_vs_transition : float
        (home possession index) × (1 - away possession index).
        High = home possession style vs away counter-attacking shape.
    sp_advantage : float
        (home sp_xg_for - home sp_xg_against) vs (away sp_xg_for - away sp_xg_against).
        Positive = home set-piece net advantage.
    aerial_edge : float
        Home aerial_duel_edge minus away aerial_duel_edge.
        Positive = home aerial superiority.
    """
    press_vs_build: float = 0.0
    width_vs_centrality: float = 0.0
    possession_vs_transition: float = 0.0
    sp_advantage: float = 0.0
    aerial_edge: float = 0.0


# ---------------------------------------------------------------------------
# Tactical engine
# ---------------------------------------------------------------------------

_DEFAULT_PPDA: float = 10.0
_DEFAULT_POSSESSION: float = 0.5


def _ewma_alpha(half_life: int) -> float:
    """Compute EWMA smoothing factor from half-life (in matches)."""
    return 1.0 - 0.5 ** (1.0 / half_life)


class TacticalEngine:
    """
    Stateful engine computing per-team TacticalProfile from rolling match data.

    Maintains TWO separate EWMA state stores:
        - Open-play xG states (open_xg_for / open_xg_against)
        - Set-piece states (sp_xg_for / sp_xg_against, corner xG, aerial)

    Removing open-play xG states does NOT affect set-piece features
    (TACTICAL-04 independence requirement).

    Parameters
    ----------
    ewma_half_life : int
        Half-life in matches for all EWMA states. Default 3.
    """

    def __init__(self, ewma_half_life: int = 3) -> None:
        self._alpha = _ewma_alpha(ewma_half_life)
        # Separate EWMA state dicts: key = team name
        self._ppda: dict[str, float] = {}
        self._possession: dict[str, float] = {}
        self._transitions: dict[str, float] = {}
        self._rest_def: dict[str, float] = {}
        # Set-piece states (TACTICAL-04: independent of open-play)
        self._sp_for: dict[str, float] = {}
        self._sp_against: dict[str, float] = {}
        self._corner_for: dict[str, float] = {}
        self._corner_against: dict[str, float] = {}
        self._aerial: dict[str, float] = {}
        # Open-play xG states (SEPARATE from set-piece)
        self._open_xg_for: dict[str, float] = {}
        self._open_xg_against: dict[str, float] = {}

    def update(self, match: MatchSummary) -> None:
        """
        Update EWMA states for a team from one MatchSummary.

        Set-piece and open-play states are updated independently.

        Parameters
        ----------
        match : MatchSummary
        """
        a = self._alpha
        t = match.team

        def _ewma(store: dict, key: str, value: float, default: float) -> None:
            store[key] = a * value + (1.0 - a) * store.get(key, default)

        # TACTICAL-01
        _ewma(self._ppda, t, match.ppda, _DEFAULT_PPDA)
        _ewma(self._possession, t, match.possession / 100.0, _DEFAULT_POSSESSION)

        # TACTICAL-02
        _ewma(self._transitions, t, float(match.transitions), 5.0)
        # Rest-defense stability = 1 - (conceded / transitions_faced)
        if match.rest_defense_transitions_faced > 0:
            rds = 1.0 - match.rest_defense_conceded / match.rest_defense_transitions_faced
        else:
            rds = 1.0
        _ewma(self._rest_def, t, max(0.0, min(1.0, rds)), 1.0)

        # TACTICAL-04: set-piece EWMA — INDEPENDENT of open-play
        _ewma(self._sp_for, t, match.sp_xg_for, 0.0)
        _ewma(self._sp_against, t, match.sp_xg_against, 0.0)

        # TACTICAL-05: corner xG + aerial
        _ewma(self._corner_for, t, match.corner_xg_for, 0.0)
        _ewma(self._corner_against, t, match.corner_xg_against, 0.0)
        _ewma(self._aerial, t, match.aerial_duels_won_rate, 0.5)

        # Open-play xG — separate state (not mixed with set-piece)
        _ewma(self._open_xg_for, t, match.open_play_xg_for, 1.0)
        _ewma(self._open_xg_against, t, match.open_play_xg_against, 1.0)

    def get_profile(self, team: str) -> TacticalProfile:
        """
        Return TacticalProfile for a team.

        If team has no data, returns a profile with sensible defaults.

        Parameters
        ----------
        team : str

        Returns
        -------
        TacticalProfile
        """
        return TacticalProfile(
            team=team,
            ppda=self._ppda.get(team, _DEFAULT_PPDA),
            possession_index=self._possession.get(team, _DEFAULT_POSSESSION),
            counterattack_freq=self._transitions.get(team, 5.0),
            rest_defense_stability=self._rest_def.get(team, 1.0),
            sp_xg_for_ewma=self._sp_for.get(team, 0.0),
            sp_xg_against_ewma=self._sp_against.get(team, 0.0),
            corner_xg_for_ewma=self._corner_for.get(team, 0.0),
            corner_xg_against_ewma=self._corner_against.get(team, 0.0),
            aerial_duel_edge=self._aerial.get(team, 0.5) - 0.5,
            open_xg_for_ewma=self._open_xg_for.get(team, 1.0),
            open_xg_against_ewma=self._open_xg_against.get(team, 1.0),
        )

    def compute_matchup(self, home_team: str, away_team: str) -> StyleMatchup:
        """
        Compute StyleMatchup interaction features for home vs away.

        Interactions are team_A_feature × opponent_B_vulnerability (TACTICAL-03).

        Parameters
        ----------
        home_team : str
        away_team : str

        Returns
        -------
        StyleMatchup
        """
        home = self.get_profile(home_team)
        away = self.get_profile(away_team)

        # TACTICAL-03: press_vs_build
        # Home pressing intensity: 1/ppda (higher = more pressing)
        # Away vulnerability to press = away possession index (high poss = susceptible)
        home_press = 1.0 / max(home.ppda, 0.1)
        press_vs_build = home_press * away.possession_index

        # TACTICAL-03: width_vs_centrality
        # Home transition frequency × away rest-defense vulnerability
        width_vs_centrality = home.counterattack_freq * (1.0 - away.rest_defense_stability)

        # TACTICAL-03: possession_vs_transition
        possession_vs_transition = home.possession_index * (1.0 - away.possession_index)

        # Set-piece advantage (home net - away net)
        home_sp_net = home.sp_xg_for_ewma - home.sp_xg_against_ewma
        away_sp_net = away.sp_xg_for_ewma - away.sp_xg_against_ewma
        sp_advantage = home_sp_net - away_sp_net

        # Aerial edge
        aerial_edge = home.aerial_duel_edge - away.aerial_duel_edge

        return StyleMatchup(
            press_vs_build=press_vs_build,
            width_vs_centrality=width_vs_centrality,
            possession_vs_transition=possession_vs_transition,
            sp_advantage=sp_advantage,
            aerial_edge=aerial_edge,
        )

    def reset_open_play_xg(self, team: str) -> None:
        """
        Remove open-play xG states for a team.

        Set-piece states are NOT affected (TACTICAL-04 independence).

        Parameters
        ----------
        team : str
        """
        self._open_xg_for.pop(team, None)
        self._open_xg_against.pop(team, None)

    def teams_with_data(self) -> list[str]:
        """Return list of all teams with at least one match update."""
        return list(self._ppda.keys())
